// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLdFABPn-DRrI3NrEnMrqOn229bVnI-0',
    appId: '1:843825700230:web:d395a7abce5b993c71a007',
    messagingSenderId: '843825700230',
    projectId: 'saving-girlfriend',
    authDomain: 'saving-girlfriend.firebaseapp.com',
    storageBucket: 'saving-girlfriend.firebasestorage.app',
    measurementId: 'G-C9WTYDG86T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_zLdpVLoLkOZ0Ul9qBWlkmPYgzCt54Y',
    appId: '1:843825700230:android:42e01764efe4fa3b71a007',
    messagingSenderId: '843825700230',
    projectId: 'saving-girlfriend',
    storageBucket: 'saving-girlfriend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1CUBID79vUqx3ktOztnU6ZgfurazxmE8',
    appId: '1:843825700230:ios:c61d66041224201071a007',
    messagingSenderId: '843825700230',
    projectId: 'saving-girlfriend',
    storageBucket: 'saving-girlfriend.firebasestorage.app',
    iosBundleId: 'com.example.savingGirlfriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1CUBID79vUqx3ktOztnU6ZgfurazxmE8',
    appId: '1:843825700230:ios:c61d66041224201071a007',
    messagingSenderId: '843825700230',
    projectId: 'saving-girlfriend',
    storageBucket: 'saving-girlfriend.firebasestorage.app',
    iosBundleId: 'com.example.savingGirlfriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyLdFABPn-DRrI3NrEnMrqOn229bVnI-0',
    appId: '1:843825700230:web:a0cd43fcee5d740371a007',
    messagingSenderId: '843825700230',
    projectId: 'saving-girlfriend',
    authDomain: 'saving-girlfriend.firebaseapp.com',
    storageBucket: 'saving-girlfriend.firebasestorage.app',
    measurementId: 'G-TD5RTMJWZE',
  );
}
