import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'package:saving_girlfriend/common/models/message.dart';
import 'package:saving_girlfriend/features/transaction/models/transaction_state.dart';

// This provider will be responsible for initializing and providing the Isar instance.
final isarProvider = FutureProvider<Isar>((ref) async {
  final dir = await getApplicationDocumentsDirectory();

  // Open the Isar database.
  // The schema list will contain all the classes annotated with @collection.
  // These schema classes are generated by the build_runner.
  final isar = await Isar.open(
    [
      // Add schemas for all collections here.
      TransactionStateSchema,
      MessageSchema,
    ],
    directory: dir.path,
  );

  return isar;
});
